#!/usr/bin/env bash
#
# Component ablation of the muscle controller on the walk task: activation
# dynamics x Hill model, 2x2. Runs the four conditions back-to-back through
# run_trials.sh (muscle only, no GIFs), N trials each:
#
#   full               activation dynamics + Hill model
#   no_actdyn          activation = command; Hill model kept
#   no_hill            linear actuator (FL = FV = 1, no passive); activation dynamics kept
#   no_actdyn_no_hill  linear actuator driven directly by the command
#
# Each condition runs the `walk` task from controllers/muscle/utils/tasks.yaml
# with an `ablation:` block added (see MuscleParams in muscle/utils/tasks.h).
# That YAML is written into the condition's folder and passed to run_trials.sh,
# so every batch keeps the exact config it ran with. tasks.yaml itself is not
# modified.
#
# Usage (from anywhere):
#   ./run_ablation_walk.sh                        # 100 trials per condition, under trials/ablation_walk/
#   ./run_ablation_walk.sh -n 5 -N ablation_pilot # pilot run
#   ./run_ablation_walk.sh --tee                  # also mirror each run's output to the terminal
#
# Output layout:
#   analysis/log/trials/<name>/<condition>/tasks.yaml
#   analysis/log/trials/<name>/<condition>/muscle/trial_NNN/{mppi_sim.csv,mppi_sim_qpos.csv,console.log}
#   analysis/log/trials/<name>/<condition>/batch_<timestamp>/{batch.log,summary.csv}
#
# Trial indices continue from whatever is already there (see run_trials.sh), so
# use a different -N for pilots, or they count toward the real trials.

set -uo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BASE_YAML="$REPO_ROOT/controllers/muscle/utils/tasks.yaml"
TRIALS_DIR="$REPO_ROOT/analysis/log/trials"

N_RUNS=100
NAME="ablation_walk"
EXTRA=()

usage() {
    sed -n '2,/^$/s/^# \?//p' "${BASH_SOURCE[0]}"
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -n|--runs) N_RUNS="$2"; shift 2 ;;
        -N|--name) NAME="$2"; shift 2 ;;
        --tee)     EXTRA+=(--tee); shift ;;
        -h|--help) usage 0 ;;
        *) echo "Unknown option: $1" >&2; usage 1 ;;
    esac
done

[[ "$N_RUNS" =~ ^[0-9]+$ && "$N_RUNS" -gt 0 ]] || { echo "-n needs a positive integer" >&2; exit 1; }
[[ "$NAME" == *".."* ]] && { echo "--name must not contain '..'" >&2; exit 1; }

# condition name -> ablation switches (empty = full model)
CONDITIONS=(full no_actdyn no_hill no_actdyn_no_hill)
declare -A FLAGS=(
    [full]=""
    [no_actdyn]="activation_dynamics=false"
    [no_hill]="use_fl=false use_fv=false use_passive=false"
    [no_actdyn_no_hill]="activation_dynamics=false use_fl=false use_fv=false use_passive=false"
)

# Write tasks.yaml with walk's ablation block set to $2 into $1.
write_yaml() {
    local out="$1" flags="$2"
    python3 - "$BASE_YAML" "$out" $flags <<'EOF'
import sys, yaml
src, out, flags = sys.argv[1], sys.argv[2], sys.argv[3:]
with open(src) as f:
    cfg = yaml.safe_load(f)
if "ablation" in cfg["walk"]:
    sys.exit(f"{src}: walk already has an ablation block; remove it so conditions start from the full model")
if flags:
    cfg["walk"]["ablation"] = {k: v == "true" for k, v in (f.split("=") for f in flags)}
with open(out, "w") as f:
    f.write(f"# Generated by run_ablation_walk.sh from {src}\n")
    f.write(f"# walk ablation: {' '.join(flags) or 'none (full model)'}\n")
    yaml.safe_dump(cfg, f, sort_keys=False)
EOF
}

ABORT=0
trap 'ABORT=1' INT TERM

START="$(date +%s)"
for cond in "${CONDITIONS[@]}"; do
    (( ABORT )) && { echo "Interrupted — not starting $cond."; break; }

    cond_dir="$TRIALS_DIR/$NAME/$cond"
    mkdir -p "$cond_dir"
    yaml="$cond_dir/tasks.yaml"
    write_yaml "$yaml" "${FLAGS[$cond]}" || { echo "Could not write $yaml" >&2; exit 1; }

    echo
    echo "════ $cond  (${FLAGS[$cond]:-full model})  —  $N_RUNS runs ════"
    "$REPO_ROOT/run_trials.sh" -t walk --muscle-only -n "$N_RUNS" \
        -N "$NAME/$cond" --muscle-yaml "$yaml" "${EXTRA[@]}"
    rc=$?
    (( rc != 0 )) && { echo "run_trials.sh exited $rc during $cond — stopping." >&2; exit "$rc"; }
done
END="$(date +%s)"

echo
echo "All conditions finished after $(( (END - START) / 60 ))m $(( (END - START) % 60 ))s."
echo "Trials: $TRIALS_DIR/$NAME/<condition>/muscle/"
